apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-eventer
  name: kube-eventer
  namespace: shoot-myqqp82xbilq4122
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-eventer
  template:
    metadata:
      labels:
        app: kube-eventer
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      # serviceAccount: kube-eventer
      containers:
        - image: fevirtus/kube-eventer:latest
          name: kube-eventer
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default?inClusterConfig=false&localKubeConfig=/etc/cloudprovider-bizflycloud/cloud-controller-manager.kubeconfig"
            - --sink=rabbitmq:?host=10.3.93.150&port=5672&username=bke_staging&password=dmNjbG91ZDE&eventstopic=dblog&vhost=bke_staging
          env:
          # If TZ is assigned, set the TZ value as the time zone
          - name: TZ
            value: "Asia/Shanghai"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
            - name: k8s-config
              mountPath: /etc/cloudprovider-bizflycloud
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
        - name: k8s-config
          configMap: 
            name: cloudprovider-bizflycloud-config